# Generated by Django 5.0.1 on 2024-02-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('subject', models.IntegerField()),
                ('author', models.CharField(max_length=230)),
            ],
        ),
    ]
